# Generated by Django 4.2.23 on 2025-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigIntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, db_column='ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, db_column='CONTACT_PERSON', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, db_column='EMAIL', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigIntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_column='NAME', max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='INVENTORY_CATEGORY',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='INVENTORY_SUPPLIER',
        ),
    ]
